main: io.kyouin.shellsec.ShellSecurity
name: ShellSecurity
version: '1.0.0'
api-version: '1.14'
description: Property over shulker boxes!
author: Kyouin
permissions:
  shellsec.claim:
    default: true
    description: Claim a shulker box.
  shellsec.bypass:
    default: op
    description: Bypass a shulker box claim.
  shellsec.alerts.*:
    default: op
    description: See alerts for claimed shulker boxes.
    children:
      shellsec.alerts.break:
        default: op
        description: See alerts when players try to break claimed shulker boxes.
      shellsec.alerts.interact:
        default: op
        description: See alerts when players try to interact with claimed shulker boxes.